Name:           ros-melodic-hebi-cpp-api
Version:        3.1.1
Release:        1%{?dist}
Summary:        ROS hebi_cpp_api package

Group:          Development/Libraries
License:        HEBI C++ Software License (https://www.hebirobotics.com/softwarelicense)
URL:            http://docs.hebi.us/tools.html#cpp-api
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  eigen3-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cmake-modules

%description
A ROS package providing access to the HEBI C++ API.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Mon Dec 16 2019 Chris Bollinger <chris@hebirobotics.com> - 3.1.1-1
- Autogenerated by Bloom

* Wed Dec 04 2019 Chris Bollinger <chris@hebirobotics.com> - 3.1.0-1
- Autogenerated by Bloom

* Wed Aug 21 2019 Matthew Tesch <matt@hebirobotics.com> - 2.1.0-1
- Autogenerated by Bloom

* Tue Jan 29 2019 Matthew Tesch <matt@hebirobotics.com> - 2.0.2-0
- Autogenerated by Bloom

* Mon Jan 28 2019 Matthew Tesch <matt@hebirobotics.com> - 2.0.1-0
- Autogenerated by Bloom

